INSERT INTO roles (nombre, nivel)
SELECT *
FROM (
    SELECT 'ROLE_ADMIN', 5
    UNION ALL
    SELECT 'ROLE_GERENTE', 2
    UNION ALL
    SELECT 'ROLE_RECEPCION', 1
    UNION ALL
    SELECT 'ROLE_OPERADOR', 1
    UNION ALL
    SELECT 'ROLE_USER', 1
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM roles LIMIT 1
);